# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0958f91e764b615aa024cfc3b1b4566fd9b6250ab2431fe32c1be71340c4bff1e08ff36715b104ba2a4fdff4aceab53caa064d9ec29a96354584a7284f7a4bdc

test:
  secret_key_base: 87fa174687c8ddeccec4283e653da6328c008e2c5b09e1dbcd16d16fd3d461444ba26b099dd93a3736416f9688caf05c764b1212c7527b9ba6c0d082cf6e750e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
